# Generated by Django 5.0.4 on 2024-04-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_detail_delete_patient_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('patiengt_name', models.CharField(max_length=200)),
                ('patient_age', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='patient_detail',
        ),
    ]
