# Generated by Django 5.0.4 on 2024-04-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_details_delete_patient_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergency_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.IntegerField()),
                ('hospitals_name', models.CharField(max_length=300)),
                ('h_address', models.CharField(max_length=200)),
                ('h_contactno', models.IntegerField()),
            ],
        ),
    ]
