# Generated by Django 5.0.4 on 2024-04-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_emergency_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='health_test_lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.CharField(max_length=10)),
                ('lab_name', models.CharField(max_length=200)),
                ('lab_address', models.CharField(max_length=300)),
                ('lab_specialisation', models.CharField(max_length=300)),
                ('las_appo_availability', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='emergency_contact',
            name='h_id',
            field=models.CharField(max_length=10),
        ),
    ]
